// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs134_MHc1B6ENNNksbMjUYypnDhP6Omo',
    appId: '1:600474771630:web:a82ff2500b2575900b8d3f',
    messagingSenderId: '600474771630',
    projectId: 'instagram-clone-8103a',
    authDomain: 'instagram-clone-8103a.firebaseapp.com',
    storageBucket: 'instagram-clone-8103a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhsUrVVtEbn065P_laYjn-EFA9YHZsmZA',
    appId: '1:600474771630:android:c6dccb7fa35d6fb80b8d3f',
    messagingSenderId: '600474771630',
    projectId: 'instagram-clone-8103a',
    storageBucket: 'instagram-clone-8103a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJL1ciOSuvRFGQNmYn_TjWumDaDakajs',
    appId: '1:600474771630:ios:a4bd4e8f7798be940b8d3f',
    messagingSenderId: '600474771630',
    projectId: 'instagram-clone-8103a',
    storageBucket: 'instagram-clone-8103a.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJL1ciOSuvRFGQNmYn_TjWumDaDakajs',
    appId: '1:600474771630:ios:a4bd4e8f7798be940b8d3f',
    messagingSenderId: '600474771630',
    projectId: 'instagram-clone-8103a',
    storageBucket: 'instagram-clone-8103a.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );
}
